title: "Segurança Aplicada a Qualidade de Software"
description: "Segurança Aplicada à Qualidade de Software - Teoria e prática para profissionais de QA em diferentes setores"
url: "https://onosendae.github.io"
baseurl: "/seguranca-qa"
author: "CWI Software"
encoding: "utf-8"
twitter:
  username: "@cwisoftware"
  card: "summary_large_image"
facebook:
  app_id: ""
image: "/assets/images/security-qa-cover.png"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  modules:
    output: true
  lessons:
    output: true
  exercises:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "modules"
      type: "modules"
    values:
      layout: module
  - scope:
      path: "lessons"
      type: "lessons"
    values:
      layout: lesson
  - scope:
      path: "modules/*/lessons/exercises"
    values:
      layout: exercise

sass:
  style: compressed

google_analytics:
  id: "G-QGD9NFSVPG"
  enabled: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - backups

