title: "Angular Expert"
description: "Treinamento intensivo e prático de Angular - Do básico ao expert em 5 dias"
url: "https://onosendae.github.io"
baseurl: "/angular"
author: "Angular Expert"
twitter:
  username: "@angular-expert"
  card: "summary_large_image"
facebook:
  app_id: ""
image: "/assets/images/podcasts/01-Fundacao_Angular_Tipagem_Encapsulamento_e_Generics.png"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  modules:
    output: true
  lessons:
    output: true
  exercises:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "modules"
      type: "modules"
    values:
      layout: module
  - scope:
      path: "lessons"
      type: "lessons"
    values:
      layout: lesson

sass:
  style: compressed

google_analytics:
  id: "G-XXXXXXXXXX"
  enabled: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

